### ISSUE TITLE
Could you add more xiangqi pieces

### ISSUE THREAD

**Issue by gaintpd** [Ka-hu/chess-pieces#1]
Hi, Could you add more xiangqi pieces, it is more than appreciated if it is possible to add the wooden theme xiangqi pieces like the gmchess wooden theme.

![Screenshot from 2020-09-02 20-39-56](https://user-images.githubusercontent.com/17960782/91982245-87d6d900-ed5c-11ea-8b2e-5ab8e8dc048d.png)

Thank you

**Comment by Kadagaden** [comment]
I'm not familiar with gmchess but if I'm not wrong this is the (official) [gmchess repository](https://github.com/lerosua/gmchess/tree/master/data/themes/wood) where you can download the pieces.

I only upload my works (new works or modifications) to this repository. Maybe in the future I'll make a new xiangqi piece set but now I don't have any xiangqi piece set to upload.

**Comment by gaintpd** [comment]
This may be a fork or a mirror of gmchess. The original gmchess repo is on google code, and the google code has been shutdown. 

This is the most popular theme in China, it is more than appreciated that you can design the similar piece based on this theme.

**Comment by gaintpd** [comment]
The wood theme in gmchess is in png format, and the pixel is 57X57, which is outdated in nowadays. I want to import this popular wood theme in cutechess as I have added xiangqi support for cutechess, which needs the skill of changing the png format to svg file format. I am not skilled to do artwork, this is the reason to open this issue, in the hope of getting help from you.

**Comment by Kadagaden** [comment]
I see. I'll try to do it sometime but it takes quite some time to make them so I can't promise that it will be soon.

**Comment by gaintpd** [comment]
Take your time, my friends, the wood theme is a popular one among many others about two decades ago, the original designer is xqwizard.

**Comment by Kadagaden** [comment]
Done! It's not a 100% match, but I hope it's similar enough. I also made a similar wooden board in svg format. 
(I might make an alternative version of this piece set sometime).

**Edit**: I updated the screenshot with the new cannon pieces with the changed Chinese characters.
![screenshot](https://i.imgur.com/9x9q5LL.png)

**Comment by gaintpd** [comment]
This is a masterpiece, this is a wonderful job, thank you very very much.

It is desirable to interchange the chinese character of the Cannon piece for the red and black side, i.e. the Chinese character of the red cannon should be "炮“ and the Chinese character of the black cannon should be "砲”, this is an error brought by xqwizard and was inherited by gmchess. 

Of course, it is all OK if keep it in the current status.

This is the screenshot in the cutechess, the 3D wood pieces make the whole board like the real wood xiangqi board. The visual effect is attractive to the chinese xiangqi fans.

![Screenshot from 2020-09-15 22-46-40](https://user-images.githubusercontent.com/17960782/93226004-6edf1680-f7a5-11ea-8a24-50c16592e7a6.png)

**Edit:** update the screenshot

**Comment by Kadagaden** [comment]
I'm happy that you like it. :) I fixed the cannon pieces, changed the Chinese characters on them. I also updated my original screenshot in my previous comment and in the README so they show the proper pieces.

**Comment by gaintpd** [comment]
Thank you very very much again and again. Highly appreciated!

**Comment by Kadagaden** [comment]
Added 2 alternative piece sets (black&red  and  a gray piece set), so I guess this issue can be closed. :)
